default: &default
  adapter: postgresql
  username: postgres
  password: user
  host: localhost

development:
  <<: *default
  database: ror_development

test:
  <<: *default
  database: ror_development # Use the same database as development

production:
  <<: *default
  database: ror_production
